name: Django                                  # workflow name

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-latest                    # similar to "image" in GitLab
    steps:
      - run: echo "This is a build step"      # similar to "script" in GitLab

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test step"
    needs: build


  integration:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
    needs: test 
    continue-on-error: true

  prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a deploy step"
    needs: integration 

  artifact:
     runs-on: ubuntu-latest
     steps:
      - run: echo "Hello World" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
           name: my-artifact
           path: hello.txt
           retention-days: 5
     needs: prod
